### ISSUE TITLE
Cannot specify dynamic field

### ISSUE THREAD

**Issue by darkbasic** [gajus/slonik-sql-tag-raw#3]
```js
const dynOrder = raw(`ORDER BY "match"."$1" ASC`, ['start_date']);
```

```js
sql`
  [...]
  ${dynOrder}
`
```

```
"stacktrace": [
            "error: column match.$24 does not exist",
            "    at Connection.parseE (/home/niko/WebstormProjects/beach/server/node_modules/pg/lib/connection.js:614:13)",
            "    at Connection.parseMessage (/home/niko/WebstormProjects/beach/server/node_modules/pg/lib/connection.js:413:19)",
            "    at Socket.<anonymous> (/home/niko/WebstormProjects/beach/server/node_modules/pg/lib/connection.js:129:22)",
            "    at Socket.emit (events.js:315:20)",
            "    at Socket.EventEmitter.emit (domain.js:485:12)",
            "    at addChunk (_stream_readable.js:297:12)",
            "    at readableAddChunk (_stream_readable.js:273:9)",
            "    at Socket.Readable.push (_stream_readable.js:214:10)",
            "    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)"
          ]
```

```raw(`ORDER BY "match"."${'start_date'}" ASC`)``` works but is not safe against SQL injection

**Comment by gajus** [comment]
https://github.com/gajus/slonik#slonik-query-building-sql-identifier
